### ISSUE TITLE
Opening too many rethinkdb connections

### ISSUE THREAD

**Issue by tizzo** [ProboCI/loom#1]
Loom seems to be opening _way_ too many connections to RethinkDB.  I'm not sure if we're inadvertently re-instantiating `rethinkdash` or if this is a bug with rethinkdash but it's hanging up our rethink server and running `lsof -i -P` even just after launching loom we can see north of 100 connections with rethinkdb.

**Comment by zanchin** [comment]
Solved in #5. 

The issue was that the DB changes feed was never being closed even through we reached the end of the Loom stream.
