### ISSUE TITLE
Starting Loom

### ISSUE THREAD

**Issue by kentr** [ProboCI/loom#9]
Following the probo quickstart  instructions 

```
cd probo-loom
node ./index.js
```

nothing appears to happen.  No output, and no process shown under `ps`.

`npm run test` returns this:

```
  auth
    all endpoints require auth
      ✓ GET /spy (140ms)
      ✓ GET /stream/id
      ✓ POST /stream/id
      ✓ POST /stream/

  FileSystemStorage
Creating a pool connected to localhost:28015
Entering slow growth mode
Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to localhost:28015\nFull error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}","message":"Failed to connect to localhost:28015\nFull error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}.","isOperational":true}
```

As far as I know, port 28015 is open.  Is Rethink not running?  There's no process with `rethink` in the command.

Any ideas?

**Comment by brianyoungblood** [comment]
@kentr did you start rethinkdb? I see mine in the netstat list - granted I'm still working on getting probo working entirely, but I do see rethink in the process list and get the same error if it's not running. Hoping this is helpful?

$ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3020            0.0.0.0:*               LISTEN      8149/probo-cm
tcp        0      0 127.0.0.1:28015         0.0.0.0:*               LISTEN      9215/rethinkdb
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      9215/rethinkdb
tcp        0      0 127.0.0.1:3060          0.0.0.0:*               LISTEN      6229/node
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:29015         0.0.0.0:*               LISTEN      9215/rethinkdb
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3010            0.0.0.0:*               LISTEN      5576/probo-ghh
tcp6       0      0 :::3050                 :::*                    LISTEN      6184/probo-proxy
tcp6       0      0 ::1:28015               :::*                    LISTEN      9215/rethinkdb
tcp6       0      0 ::1:8080                :::*                    LISTEN      9215/rethinkdb
tcp6       0      0 :::80                   :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 ::1:29015               :::*                    LISTEN      9215/rethinkdb
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp        0      0 0.0.0.0:55699           0.0.0.0:*                           -
udp        0      0 0.0.0.0:55845           0.0.0.0:*                           -
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -
udp6       0      0 :::63703                :::*                                -
udp6       0      0 ::1:323                 :::*                                -

**Comment by kentr** [comment]
@brianyoungblood

> did you start rethinkdb?

Ehhh, no.  In my noobness to node / npm, I thought rethink was supposed to be installed / started automatically as a dependency.

Thanks for the clue ;-)

**Comment by kentr** [comment]
@brianyoungblood In case you're interested, I'm working on a Vagrant / Ansible deployment of ProboCI [here](https://github.com/kentr/probo-ci-vagrant/).

**Comment by brianyoungblood** [comment]
@kentr sounds interesting. I'll check it out.

**Comment by kentr** [comment]
Installing / starting rethinkdb solved this.
